package AllClass;

import javax.swing.*;
import javax.swing.border.Border;

import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class ViewAll_roots extends JFrame implements ActionListener {
	 private JLabel jl;
	 private JPanel jp,jp1,jp2,jp3;
	 private JTextField jt,jt1,jt2,jt3,jt4,jt5,jt6,jt7,jt8,jt9,jt10,jt11,jt12,jt13,jt14,jt15,jt16,jt17,jt18,jt19,jt20,jt21,jt22,jt23,
	                    jt24,jt25,jt26,jt27,jt28,jt29,jt30,jt31,jt32,jt33,jt34,jt35,jt36,jt37,jt38,jt39,jt40,jt41,jt42,jt43,jt44,jt45,jt46,jt47,
	                    jt48,jt49,jt50,jt51,jt52,jt53,jt54,jt55,jt56,jt57,jt58,jt59,jt60,jt61,jt62,jt63,jt64,jt65,jt66,jt67,jt68,jt69,jt70,jt71,
	                    jt72,jt73,jt74,jt75,jt76,jt77,jt78,jt79,jt80,jt81,jt82,jt83,jt84,jt85,jt86,jt87,jt88,jt89,jt90,jt91,jt92,jt93,jt94,jt95,jt96,jt97,
	                    jt98,jt99,jt100,jt101,jt102,jt103,jt104,jt105,jt106,jt107,jt108,jt109,jt110,jt111;
	 
	 Icon icon1 = new ImageIcon("G:\\Yonas DB\\Computer\\Programing\\Demo2\\Java\\BusProject\\src\\AllClass\\b10.png");
	 Image icon = Toolkit.getDefaultToolkit().getImage("G:\\Yonas DB\\Computer\\Programing\\Demo2\\Java\\BusProject\\src\\AllClass\\icon2.png");
			
	 
	private JLabel jl0,jl01,jl02,jl03;
	private JPanel jp0,jp01,jp02,jp03,jp04,jp05,jp06,jp07;
	private JButton jb0,jb01,jb02,jb03,jb04;
	private JButton back;
	 String [] st;
	 int count1;
	
	 public ViewAll_roots(int count) {
		 this.count1=count;
	 }
	 
	/* String []Fname= new String[count1];
	String [] Lname= new String[count1];
	String [] pay_km= new String[count1];
	String [] noStationS= new String[count1];
	String [] no_busesS= new String[count1];
	String [] end_kmS=new String[count1];*/
	public ViewAll_roots(int count,String []Fname,String [] Lname,String [] pay_km,String [] noStationS,String [] end_kmS ,String [] no_busesS,String [] bus_no1) {
		 
		setIconImage(icon); 
		
		jp0= new JPanel();
		jp01= new JPanel();
		jp02= new JPanel();
		jp03= new JPanel();
		jp04= new JPanel();
		jp05= new JPanel();
		jp06= new JPanel();
		jp07= new JPanel();
	
		
		    jp = new JPanel(new BorderLayout());
		    jp2 = new JPanel(new FlowLayout());
		    jp3 = new JPanel(new FlowLayout());
		    getContentPane().add(jp0);
		  
		    back = new JButton("Back");
		    back=new JButton(icon1);
	        //back.setFont(new Font("Arial", Font.PLAIN, 18));
			back.setText("");
		    back.setBackground(Color.decode("#F0F8FF"));
		    back.setForeground(Color.decode("#F0F8FF"));
		    back.setBorder(BorderFactory.createLineBorder(Color.decode("#F0F8FF")));
		    back.setSize(40, 30);
		    
		    jb0= new JButton("List all root");
			jb01= new JButton("View spacific root");
			//jb02= new JButton("View spacific root payment");
			jb03= new JButton("View spacific root waiting time");
			//jb04= new JButton("View spacific root payment bus distance");
			
			jl0= new JLabel("ABC CITY BUS TRACKING SYSTEM");
			jl01= new JLabel("                  ");
			jl02= new JLabel("                   ");
			jl03= new JLabel(" ");
			jl03.setFont(new Font("Verdana",Font.BOLD,29));
			jl0.setBounds(50, 100, 200, 50);
			jl0.setFont(new Font("Verdana",Font.BOLD,29));
			jl0.setForeground(Color.BLUE);
			
			//back.setBounds(30, 100, 120, 20);
			//back.setBackground(Color.ORANGE);
			jb0.setBounds(30, 100, 100, 20);
			jb0.setBackground(Color.orange);
			jb01.setBounds(30, 100, 100, 20);
			jb01.setBackground(Color.CYAN);
			//jb02.setBounds(30, 100, 100, 20);
			//jb02.setBackground(Color.CYAN);
			jb03.setBounds(30, 100, 100, 20);
			jb03.setBackground(Color.CYAN);
			//jb04.setBounds(30, 100, 100, 20);
			//jb04.setBackground(Color.CYAN);
			
			jp0.setLayout(new BorderLayout());
			jp01.setLayout(new BorderLayout());
			jp02.setLayout(new BorderLayout());
			jp03.setLayout(new FlowLayout());
			jp04.setLayout(new FlowLayout());
			jp05.setLayout(new FlowLayout());
			jp06.setLayout(new FlowLayout());
			jp07.setLayout(new FlowLayout());
			
			
			//cp.add(jp0);
			jp0.add(jp01,BorderLayout.CENTER);
			jp0.add(jp04,BorderLayout.NORTH);
			jp04.add(jl0);
			jp01.add(jp02,BorderLayout.CENTER);
			jp02.add(jp03,BorderLayout.NORTH);
			
			jp01.add(jp05,BorderLayout.SOUTH);
			jp05.add(jl02);
			jp01.add(jp06,BorderLayout.EAST);
			jp06.add(jl01);
			jp01.add(jp07,BorderLayout.WEST);
			jp07.add(jl02);
			
			Border blue = BorderFactory.createLineBorder(Color.BLUE);
			jp02.setBorder(blue);
			
			jp03.add(back);
			jp03.add(jb0);
			jp03.add(jb01);
			//jp03.add(jb02);
			jp03.add(jb03);
			//jp03.add(jb04);
			
			jp02.add(jp,BorderLayout.CENTER);
		    
		    jl=new JLabel();
		    jl.setText("City's all bus roots");
		    jl.setFont(new Font("Arial", Font.BOLD, 29));
	        jl.setForeground(Color.BLACK);
	        
	        
		    jp1 = new JPanel(new GridLayout( count+1, 8, 10, 10));
		    jt=new JTextField();
		    jt.setText("S.N");
		    jt.setFont(new Font("Arial", Font.BOLD, 13));
		    jt.setEditable(false);
		    jt.setColumns(10);
		    jt.setBackground(Color.pink);
		    jt111=new JTextField();
		    jt111.setText("Buse no");
		    jt111.setFont(new Font("Arial", Font.BOLD, 13));
		    jt111.setEditable(false);
		    jt111.setColumns(10);
		    jt111.setBackground(Color.pink);
		    jt1=new JTextField();
		    jt1.setText("From");
		    jt1.setFont(new Font("Arial", Font.BOLD, 13));
		    jt1.setEditable(false);
		    jt1.setColumns(10);
		    jt1.setBackground(Color.pink);
		    jt2=new JTextField();
		    jt2.setText("To");
		    jt2.setFont(new Font("Arial", Font.BOLD, 13));
		    jt2.setEditable(false);
		    jt2.setColumns(10);
		    jt2.setBackground(Color.pink);
		    jt3=new JTextField();
		    jt3.setText("No of Stations");
		    jt3.setFont(new Font("Arial", Font.BOLD, 13));
		    jt3.setEditable(false);
		    jt3.setColumns(10);
		    jt3.setBackground(Color.pink);
		    jt4=new JTextField();
		    jt4.setText("Payment/KM");
		    jt4.setFont(new Font("Arial", Font.BOLD, 13));
		    jt4.setEditable(false);
		    jt4.setColumns(10);
		    jt4.setFont(new Font("Arial", Font.BOLD, 13));
		    jt4.setBackground(Color.pink);
		    jt5=new JTextField();
		    jt5.setText("Distance in km");
		    jt5.setEditable(false);
		    jt5.setColumns(12);
		    jt5.setFont(new Font("Arial", Font.BOLD, 13));
		    jt5.setBackground(Color.pink);
		    jt6=new JTextField();
		    jt6.setText("No of buses");
		    jt6.setFont(new Font("Arial", Font.BOLD, 13));
		    jt6.setEditable(false);
		    jt6.setColumns(10);
		    jt6.setBackground(Color.pink);
		    jt7=new JTextField();
		    jt7.setText("1");
		    jt7.setFont(new Font("Arial", Font.BOLD, 13));
		    jt7.setEditable(false);
		    jt7.setColumns(10);
		    jt7.setForeground(Color.YELLOW);
		    jt7.setBackground(Color.darkGray);
		    jt8=new JTextField();
		    jt8.setEditable(false);
		    jt8.setColumns(10);
		    jt8.setForeground(Color.WHITE);
		    jt8.setBackground(Color.darkGray);
		    jt9=new JTextField();
		    jt9.setEditable(false);
		    jt9.setColumns(10);
		    jt9.setForeground(Color.WHITE);
		    jt9.setBackground(Color.darkGray);
		    jt10=new JTextField();
		    jt10.setEditable(false);
		    jt10.setColumns(10);
		    jt10.setForeground(Color.WHITE);
		    jt10.setBackground(Color.darkGray);
		    jt11=new JTextField();
		    jt11.setEditable(false);
		    jt11.setColumns(10);
		    jt11.setForeground(Color.WHITE);
		    jt11.setBackground(Color.darkGray);
		    jt12=new JTextField();
		    jt12.setEditable(false);
		    jt12.setColumns(10);
		    jt12.setForeground(Color.WHITE);
		    jt12.setBackground(Color.darkGray);
		    jt13=new JTextField();
		    jt13.setEditable(false);
		    jt13.setColumns(10);
		    jt13.setForeground(Color.WHITE);
		    jt13.setBackground(Color.darkGray);
		    jt14=new JTextField();
		    jt14.setText("2");
		    jt14.setFont(new Font("Arial", Font.BOLD, 13));
		    jt14.setEditable(false);
		    jt14.setColumns(10);
		    jt14.setForeground(Color.YELLOW);
		    jt14.setBackground(Color.darkGray);
		    jt15=new JTextField();
		    jt15.setEditable(false);
		    jt15.setColumns(10);
		    jt15.setForeground(Color.WHITE);
		    jt15.setBackground(Color.darkGray);
		    jt16=new JTextField();
		    jt16.setEditable(false);
		    jt16.setColumns(10);
		    jt16.setForeground(Color.WHITE);
		    jt16.setBackground(Color.darkGray);
		    jt17=new JTextField();
		    jt17.setEditable(false);
		    jt17.setColumns(10);
		    jt17.setForeground(Color.WHITE);
		    jt17.setBackground(Color.darkGray);
		    jt18=new JTextField();
		    jt18.setEditable(false);
		    jt18.setColumns(10);
		    jt18.setForeground(Color.WHITE);
		    jt18.setBackground(Color.darkGray);
		    jt19=new JTextField();
		    jt19.setEditable(false);
		    jt19.setColumns(10);
		    jt19.setForeground(Color.WHITE);
		    jt19.setBackground(Color.darkGray);
		    jt20=new JTextField();
		    jt20.setEditable(false);
		    jt20.setColumns(10);
		    jt20.setForeground(Color.WHITE);
		    jt20.setBackground(Color.darkGray);
		    jt21=new JTextField();
		    jt21.setText("3");
		    jt21.setFont(new Font("Arial", Font.BOLD, 13));
		    jt21.setEditable(false);
		    jt21.setColumns(10);
		    jt21.setForeground(Color.YELLOW);
		    jt21.setBackground(Color.darkGray);
		    jt22=new JTextField();
		    jt22.setEditable(false);
		    jt22.setColumns(10);
		    jt22.setForeground(Color.WHITE);
		    jt22.setBackground(Color.darkGray);
		    jt23=new JTextField();
		    jt23.setEditable(false);
		    jt23.setColumns(10);
		    jt23.setForeground(Color.WHITE);
		    jt23.setBackground(Color.darkGray);
		    
		    jt24=new JTextField();
		    jt24.setEditable(false);
		    jt24.setColumns(10);
		    jt24.setForeground(Color.WHITE);
		    jt24.setBackground(Color.darkGray);
		    jt25=new JTextField();
		    jt25.setEditable(false);
		    jt25.setColumns(10);
		    jt25.setForeground(Color.WHITE);
		    jt25.setBackground(Color.darkGray);
		    jt26=new JTextField();
		    jt26.setEditable(false);
		    jt26.setColumns(10);
		    jt26.setForeground(Color.WHITE);
		    jt26.setBackground(Color.darkGray);
		    jt27=new JTextField();
		    jt27.setEditable(false);
		    jt27.setColumns(10);
		    jt27.setForeground(Color.WHITE);
		    jt27.setBackground(Color.darkGray);
		    jt28=new JTextField();
		    jt28.setText("4");
		    jt28.setFont(new Font("Arial", Font.BOLD, 13));
		    jt28.setEditable(false);
		    jt28.setColumns(10);
		    jt28.setForeground(Color.YELLOW);
		    jt28.setBackground(Color.darkGray);
		    jt29=new JTextField();
		    jt29.setEditable(false);
		    jt29.setColumns(10);
		    jt29.setForeground(Color.WHITE);
		    jt29.setBackground(Color.darkGray);
		    jt30=new JTextField();
		    jt30.setEditable(false);
		    jt30.setColumns(10);
		    jt30.setForeground(Color.WHITE);
		    jt30.setBackground(Color.darkGray);
		    jt31=new JTextField();
		    jt31.setEditable(false);
		    jt31.setColumns(10);
		    jt31.setForeground(Color.WHITE);
		    jt31.setBackground(Color.darkGray);
		    jt32=new JTextField();
		    jt32.setEditable(false);
		    jt32.setColumns(10);
		    jt32.setForeground(Color.WHITE);
		    jt32.setBackground(Color.darkGray);
		    jt33=new JTextField();
		    jt33.setEditable(false);
		    jt33.setColumns(10);
		    jt33.setForeground(Color.WHITE);
		    jt33.setBackground(Color.darkGray);
		    jt34=new JTextField();
		    jt34.setEditable(false);
		    jt34.setColumns(10);
		    jt34.setForeground(Color.WHITE);
		    jt34.setBackground(Color.darkGray);
		    jt35=new JTextField();
		    jt35=new JTextField();
		    jt35.setText("5");
		    jt35.setFont(new Font("Arial", Font.BOLD, 13));
		    jt35.setEditable(false);
		    jt35.setColumns(10);
		    jt35.setForeground(Color.YELLOW);
		    jt35.setBackground(Color.darkGray);
		    jt36=new JTextField();
		    jt36.setEditable(false);
		    jt36.setColumns(10);
		    jt36.setForeground(Color.WHITE);
		    jt36.setBackground(Color.darkGray);
		    jt37=new JTextField();
		    jt37.setEditable(false);
		    jt37.setColumns(10);
		    jt37.setForeground(Color.WHITE);
		    jt37.setBackground(Color.darkGray);
		    jt38=new JTextField();
		    jt38.setEditable(false);
		    jt38.setColumns(10);
		    jt38.setForeground(Color.WHITE);
		    jt38.setBackground(Color.darkGray);
		    jt39=new JTextField();
		    jt39.setEditable(false);
		    jt39.setColumns(10);
		    jt39.setForeground(Color.WHITE);
		    jt39.setBackground(Color.darkGray);
		    jt40=new JTextField();
		    jt40.setEditable(false);
		    jt40.setColumns(10);
		    jt40.setForeground(Color.WHITE);
		    jt40.setBackground(Color.darkGray);
		    jt41=new JTextField();
		    jt41.setEditable(false);
		    jt41.setColumns(10);
		    jt41.setForeground(Color.WHITE);
		    jt41.setBackground(Color.darkGray);
		    jt42=new JTextField();
		    jt42.setText("6");
		    jt42.setFont(new Font("Arial", Font.BOLD, 13));
		    jt42.setEditable(false);
		    jt42.setColumns(10);
		    jt42.setForeground(Color.YELLOW);
		    jt42.setBackground(Color.darkGray);
		    jt43=new JTextField();
		    jt43.setEditable(false);
		    jt43.setColumns(10);
		    jt43.setForeground(Color.WHITE);
		    jt43.setBackground(Color.darkGray);
		    jt44=new JTextField();
		    jt44.setEditable(false);
		    jt44.setColumns(10);
		    jt44.setForeground(Color.WHITE);
		    jt44.setBackground(Color.darkGray);
		    jt45=new JTextField();
		    jt45.setEditable(false);
		    jt45.setColumns(10);
		    jt45.setForeground(Color.WHITE);
		    jt45.setBackground(Color.darkGray);
		    jt46=new JTextField();
		    jt46.setEditable(false);
		    jt46.setColumns(10);
		    jt46.setForeground(Color.WHITE);
		    jt46.setBackground(Color.darkGray);
		    jt47=new JTextField();
		    jt47.setEditable(false);
		    jt47.setColumns(10);
		    jt47.setForeground(Color.WHITE);
		    jt47.setBackground(Color.darkGray);
		    
		    
		    jt48=new JTextField();
		    jt48.setEditable(false);
		    jt48.setColumns(10);
		    jt48.setForeground(Color.WHITE);
		    jt48.setBackground(Color.darkGray);
		    jt49=new JTextField();
		    jt49.setText("7");
		    jt49.setFont(new Font("Arial", Font.BOLD, 13));
		    jt49.setEditable(false);
		    jt49.setColumns(10);
		    jt49.setForeground(Color.YELLOW);
		    jt49.setBackground(Color.darkGray);
		    jt50=new JTextField();
		    jt50.setEditable(false);
		    jt50.setColumns(10);
		    jt50.setForeground(Color.WHITE);
		    jt50.setBackground(Color.darkGray);
		    jt51=new JTextField();
		    jt51.setEditable(false);
		    jt51.setColumns(10);
		    jt51.setForeground(Color.WHITE);
		    jt51.setBackground(Color.darkGray);
		    jt52=new JTextField();
		    jt52.setEditable(false);
		    jt52.setColumns(10);
		    jt52.setForeground(Color.WHITE);
		    jt52.setBackground(Color.darkGray);
		    jt53=new JTextField();
		    jt53.setEditable(false);
		    jt53.setColumns(10);
		    jt53.setForeground(Color.WHITE);
		    jt53.setBackground(Color.darkGray);
		    jt54=new JTextField();
		    jt34.setEditable(false);
		    jt54.setColumns(10);
		    jt54.setForeground(Color.WHITE);
		    jt54.setBackground(Color.darkGray);
		    jt55=new JTextField();
		    jt55.setEditable(false);
		    jt55.setColumns(10);
		    jt55.setForeground(Color.WHITE);
		    jt55.setBackground(Color.darkGray);
		    jt56=new JTextField();
		    jt56.setText("8");
		    jt56.setFont(new Font("Arial", Font.BOLD, 13));
		    jt56.setEditable(false);
		    jt56.setColumns(10);
		    jt56.setForeground(Color.YELLOW);
		    jt56.setBackground(Color.darkGray);
		    jt57=new JTextField();
		    jt57.setEditable(false);
		    jt57.setColumns(10);
		    jt57.setForeground(Color.WHITE);
		    jt57.setBackground(Color.darkGray);
		    jt58=new JTextField();
		    jt58.setEditable(false);
		    jt58.setColumns(10);
		    jt58.setForeground(Color.WHITE);
		    jt58.setBackground(Color.darkGray);
		    jt59=new JTextField();
		    jt59.setEditable(false);
		    jt59.setColumns(10);
		    jt59.setForeground(Color.WHITE);
		    jt59.setBackground(Color.darkGray);
		    jt60=new JTextField();
		    jt60.setEditable(false);
		    jt60.setColumns(10);
		    jt60.setForeground(Color.WHITE);
		    jt60.setBackground(Color.darkGray);
		    jt61=new JTextField();
		    jt61.setEditable(false);
		    jt61.setColumns(10);
		    jt61.setForeground(Color.WHITE);
		    jt61.setBackground(Color.darkGray);
		    jt62=new JTextField();
		    jt62.setEditable(false);
		    jt62.setColumns(10);
		    jt62.setForeground(Color.WHITE);
		    jt62.setBackground(Color.darkGray);
		    jt63=new JTextField();
		    jt63.setText("9");
		    jt63.setFont(new Font("Arial", Font.BOLD, 13));
		    jt63.setEditable(false);
		    jt63.setColumns(10);
		    jt63.setForeground(Color.YELLOW);
		    jt63.setBackground(Color.darkGray);
		    jt64=new JTextField();
		    jt64.setEditable(false);
		    jt64.setColumns(10);
		    jt64.setForeground(Color.WHITE);
		    jt64.setBackground(Color.darkGray);
		    jt65=new JTextField();
		    jt65.setEditable(false);
		    jt65.setColumns(10);
		    jt65.setForeground(Color.WHITE);
		    jt65.setBackground(Color.darkGray);
		    jt66=new JTextField();
		    jt66.setEditable(false);
		    jt66.setColumns(10);
		    jt66.setForeground(Color.WHITE);
		    jt66.setBackground(Color.darkGray);
		    jt67=new JTextField();
		    jt67.setEditable(false);
		    jt67.setColumns(10);
		    jt67.setForeground(Color.WHITE);
		    jt67.setBackground(Color.darkGray);
		    jt68=new JTextField();
		    jt68.setEditable(false);
		    jt68.setColumns(10);
		    jt68.setForeground(Color.WHITE);
		    jt68.setBackground(Color.darkGray);
		    jt69=new JTextField();
		    jt69.setEditable(false);
		    jt69.setColumns(10);
		    jt69.setForeground(Color.WHITE);
		    jt69.setBackground(Color.darkGray);
		    jt70=new JTextField();
		    jt70.setText("10");
		    jt70.setFont(new Font("Arial", Font.BOLD, 13));
		    jt70.setEditable(false);
		    jt70.setColumns(10);
		    jt70.setForeground(Color.YELLOW);
		    jt70.setBackground(Color.darkGray);
		    jt71=new JTextField();
		    jt71.setEditable(false);
		    jt71.setColumns(10);
		    jt71.setForeground(Color.WHITE);
		    jt71.setBackground(Color.darkGray);
		    
		    jt72=new JTextField();
		    jt72.setEditable(false);
		    jt72.setColumns(10);
		    jt72.setForeground(Color.WHITE);
		    jt72.setBackground(Color.darkGray);
		    jt73=new JTextField();
		    jt73.setEditable(false);
		    jt73.setColumns(10);
		    jt73.setForeground(Color.WHITE);
		    jt73.setBackground(Color.darkGray);
		    jt74=new JTextField();
		    jt74.setEditable(false);
		    jt74.setColumns(10);
		    jt74.setForeground(Color.WHITE);
		    jt74.setBackground(Color.darkGray);
		    jt75=new JTextField();
		    jt75.setEditable(false);
		    jt75.setColumns(10);
		    jt75.setForeground(Color.WHITE);
		    jt75.setBackground(Color.darkGray);
		    jt76=new JTextField();
		    jt76.setEditable(false);
		    jt76.setColumns(10);
		    jt76.setForeground(Color.WHITE);
		    jt76.setBackground(Color.darkGray);
		    jt77=new JTextField();
		    jt77.setText("11");
		    jt77.setFont(new Font("Arial", Font.BOLD, 13));
		    jt77.setEditable(false);
		    jt77.setColumns(10);
		    jt77.setForeground(Color.YELLOW);
		    jt77.setBackground(Color.darkGray);
		    jt78=new JTextField();
		    jt78.setEditable(false);
		    jt78.setColumns(10);
		    jt78.setForeground(Color.WHITE);
		    jt78.setBackground(Color.darkGray);
		    jt79=new JTextField();
		    jt79.setEditable(false);
		    jt79.setColumns(10);
		    jt79.setForeground(Color.WHITE);
		    jt79.setBackground(Color.darkGray);
		    jt80=new JTextField();
		    jt80.setEditable(false);
		    jt80.setColumns(10);
		    jt80.setForeground(Color.WHITE);
		    jt80.setBackground(Color.darkGray);
		    jt81=new JTextField();
		    jt81.setEditable(false);
		    jt81.setColumns(10);
		    jt81.setForeground(Color.WHITE);
		    jt81.setBackground(Color.darkGray);
		    jt82=new JTextField();
		    jt82.setEditable(false);
		    jt82.setColumns(10);
		    jt82.setForeground(Color.WHITE);
		    jt82.setBackground(Color.darkGray);
		    jt83=new JTextField();
		    jt83.setEditable(false);
		    jt83.setColumns(10);
		    jt83.setForeground(Color.WHITE);
		    jt83.setBackground(Color.darkGray);
		    jt84=new JTextField();
		    jt84.setEditable(false);
		    jt84.setColumns(10);
		    jt84.setForeground(Color.WHITE);
		    jt84.setBackground(Color.darkGray);
		    jt85=new JTextField();
		    jt85.setEditable(false);
		    jt85.setColumns(10);
		    jt85.setForeground(Color.WHITE);
		    jt85.setBackground(Color.darkGray);
		    jt86=new JTextField();
		    jt86.setEditable(false);
		    jt86.setColumns(10);
		    jt86.setForeground(Color.WHITE);
		    jt86.setBackground(Color.darkGray);
		    jt87=new JTextField();
		    jt87.setEditable(false);
		    jt87.setColumns(10);
		    jt87.setForeground(Color.WHITE);
		    jt87.setBackground(Color.darkGray);
		    jt88=new JTextField();
		    jt88.setEditable(false);
		    jt88.setColumns(10);
		    jt88.setForeground(Color.WHITE);
		    jt88.setBackground(Color.darkGray);
		    jt89=new JTextField();
		    jt89.setEditable(false);
		    jt89.setColumns(10);
		    jt89.setForeground(Color.WHITE);
		    jt89.setBackground(Color.darkGray);
		    jt90=new JTextField();
		    jt90.setEditable(false);
		    jt90.setColumns(10);
		    jt90.setForeground(Color.WHITE);
		    jt90.setBackground(Color.darkGray);
		    jt91=new JTextField();
		    jt91.setEditable(false);
		    jt91.setColumns(10);
		    jt91.setForeground(Color.WHITE);
		    jt91.setBackground(Color.darkGray);
		    jt92=new JTextField();
		    jt92.setEditable(false);
		    jt92.setColumns(10);
		    jt92.setForeground(Color.WHITE);
		    jt92.setBackground(Color.darkGray);
		    jt93=new JTextField();
		    jt93.setEditable(false);
		    jt93.setColumns(10);
		    jt93.setForeground(Color.WHITE);
		    jt93.setBackground(Color.darkGray);
		    jt94=new JTextField();
		    jt94.setEditable(false);
		    jt94.setColumns(10);
		    jt94.setForeground(Color.WHITE);
		    jt94.setBackground(Color.darkGray);
		    jt95=new JTextField();
		    jt95.setEditable(false);
		    jt95.setColumns(10);
		    jt95.setForeground(Color.WHITE);
		    jt95.setBackground(Color.darkGray);
		    jt96=new JTextField();
		    jt96.setEditable(false);
		    jt96.setColumns(10);
		    jt96.setForeground(Color.WHITE);
		    jt96.setBackground(Color.darkGray);
		    jt97=new JTextField();
		    jt97.setEditable(false);
		    jt97.setColumns(10);
		    jt97.setForeground(Color.WHITE);
		    jt97.setBackground(Color.darkGray);
		    jt98=new JTextField();
		    jt98.setEditable(false);
		    jt98.setColumns(10);
		    jt98.setForeground(Color.WHITE);
		    jt98.setBackground(Color.darkGray);
		    jt99=new JTextField();
		    jt99.setEditable(false);
		    jt99.setColumns(10);
		    jt99.setForeground(Color.WHITE);
		    jt99.setBackground(Color.darkGray);
		    jt100=new JTextField();
		    jt100.setEditable(false);
		    jt100.setColumns(10);
		    jt100.setForeground(Color.WHITE);
		    jt100.setBackground(Color.darkGray);
		    jt101=new JTextField();
		    jt101.setEditable(false);
		    jt101.setColumns(10);
		    jt101.setForeground(Color.WHITE);
		    jt101.setBackground(Color.darkGray);
		    jt102=new JTextField();
		    jt102.setEditable(false);
		    jt102.setColumns(10);
		    jt102.setForeground(Color.WHITE);
		    jt102.setBackground(Color.darkGray);
		    jt103=new JTextField();
		    jt103.setEditable(false);
		    jt103.setColumns(10);
		    jt103.setForeground(Color.WHITE);
		    jt103.setBackground(Color.darkGray);
		    jt104=new JTextField();
		    jt104.setEditable(false);
		    jt104.setColumns(10);
		    jt104.setForeground(Color.WHITE);
		    jt104.setBackground(Color.darkGray);
		    jt105=new JTextField();
		    jt105.setEditable(false);
		    jt105.setColumns(10);
		    jt105.setForeground(Color.WHITE);
		    jt105.setBackground(Color.darkGray);
		    jt106=new JTextField();
		    jt106.setEditable(false);
		    jt106.setColumns(10);
		    jt106.setForeground(Color.WHITE);
		    jt106.setBackground(Color.darkGray);
		    jt107=new JTextField();
		    jt107.setEditable(false);
		    jt107.setColumns(10);
		    jt107.setForeground(Color.WHITE);
		    jt107.setBackground(Color.darkGray);
		    jt108=new JTextField();
		    jt108.setEditable(false);
		    jt108.setColumns(10);
		    jt108.setForeground(Color.WHITE);
		    jt108.setBackground(Color.darkGray);
		    jt109=new JTextField();
		    jt109.setEditable(false);
		    jt109.setColumns(10);
		    jt109.setForeground(Color.WHITE);
		    jt109.setBackground(Color.darkGray);
		    jt110=new JTextField();
		    jt110.setEditable(false);
		    jt110.setColumns(10);
		    jt110.setForeground(Color.WHITE);
		    jt110.setBackground(Color.darkGray);
		    // Adding JButton "btn1" on JPanel.
		    jp1.add(jt);
		    jp1.add(jt111);
		    jp1.add(jt1);
		    jp1.add(jt2);
		    jp1.add(jt3);
		    jp1.add(jt4);
		    jp1.add(jt5);
		    jp1.add(jt6);
		    
		    if(count>=1) {
		    jp1.add(jt7);
		    jp1.add(jt98);
		    jp1.add(jt8);
		    jp1.add(jt9);
		    jp1.add(jt10);
		    jp1.add(jt11);
		    jp1.add(jt12);
		    jp1.add(jt13);
		    jt98.setText(bus_no1[0]);
		    jt8.setText(Fname[0]);
		    jt9.setText(Lname[0]);
		    jt10.setText(noStationS[0]);
		    jt11.setText(pay_km[0]);  
		    jt12.setText(end_kmS[0]);
		    jt13.setText(no_busesS[0]);
		    }if(count>=2) {
		    jp1.add(jt14);
		    jp1.add(jt99);
		    jp1.add(jt15);
		    jp1.add(jt16);
		    jp1.add(jt17);
		    jp1.add(jt18);
		    jp1.add(jt19);
		    jp1.add(jt20);
		    jt99.setText(bus_no1[1]);
		    jt15.setText(Fname[1]);
		    jt16.setText(Lname[1]);
		    jt17.setText(noStationS[1]);
		    jt18.setText(pay_km[1]);
		    jt19.setText(end_kmS[1]);
		    jt20.setText(no_busesS[1]);
		    }if(count>=3) {
		    jp1.add(jt21);
		    jp1.add(jt100);
		    jp1.add(jt22);
		    jp1.add(jt23);
		    jp1.add(jt24);
		    jp1.add(jt25);
		    jp1.add(jt26);
		    jp1.add(jt27);
		    jt100.setText(bus_no1[2]);
		    jt22.setText(Fname[2]);
		    jt23.setText(Lname[2]);
		    jt24.setText(noStationS[2]);
		    jt25.setText(pay_km[2]);
		    jt26.setText(end_kmS[2]);
		    jt27.setText(no_busesS[2]);
		    }if(count>=4) {
		    jp1.add(jt28);
		    jp1.add(jt101);
		    jp1.add(jt29);
		    jp1.add(jt30);
		    jp1.add(jt31);
		    jp1.add(jt32);
		    jp1.add(jt33);
		    jp1.add(jt34);
		    jt101.setText(bus_no1[3]);
		    jt29.setText(Fname[3]);
		    jt30.setText(Lname[3]);
		    jt31.setText(noStationS[3]);
		    jt32.setText(pay_km[3]);
		    jt33.setText(end_kmS[3]);
		    jt34.setText(no_busesS[3]);
		    }if(count>=5) {
		    jp1.add(jt35);
		    jp1.add(jt102);
		    jp1.add(jt36);
		    jp1.add(jt37);
		    jp1.add(jt38);
		    jp1.add(jt39);
		    jp1.add(jt40);
		    jp1.add(jt41);
		    jt102.setText(bus_no1[4]);
		    jt36.setText(Fname[4]);
		    jt37.setText(Lname[4]);
		    jt38.setText(noStationS[4]);
		    jt39.setText(pay_km[4]);
		    jt40.setText(end_kmS[4]);
		    jt41.setText(no_busesS[4]);
		    }if(count>=6) {
		    jp1.add(jt42);
		    jp1.add(jt103);
		    jp1.add(jt43);
		    jp1.add(jt44);
		    jp1.add(jt45);
		    jp1.add(jt46);
		    jp1.add(jt47);
		    jp1.add(jt48);
		    jt103.setText(bus_no1[5]);
		    jt43.setText(Fname[5]);
		    jt44.setText(Lname[5]);
		    jt45.setText(noStationS[5]);
		    jt46.setText(pay_km[5]);
		    jt47.setText(end_kmS[5]);
		    jt48.setText(no_busesS[5]);
		    }if(count>=7) {
		    jp1.add(jt49);
		    jp1.add(jt104);
		    jp1.add(jt50);
		    jp1.add(jt51);
		    jp1.add(jt52);
		    jp1.add(jt53);
		    jp1.add(jt54);
		    jp1.add(jt55);
		    jt104.setText(bus_no1[6]);
		    jt50.setText(Fname[6]);
		    jt51.setText(Lname[6]);
		    jt52.setText(noStationS[6]);
		    jt53.setText(pay_km[6]);
		    jt54.setText(end_kmS[6]);
		    jt55.setText(no_busesS[6]);
		    }if(count>=8) {
		    jp1.add(jt56);
		    jp1.add(jt105);
		    jp1.add(jt57);
		    jp1.add(jt58);
		    jp1.add(jt59);
		    jp1.add(jt60);
		    jp1.add(jt61);
		    jp1.add(jt62);
		    jt105.setText(bus_no1[7]);
		    jt57.setText(Fname[7]);
		    jt58.setText(Lname[7]);
		    jt59.setText(noStationS[7]);
		    jt60.setText(pay_km[7]);
		    jt61.setText(end_kmS[7]);
		    jt62.setText(no_busesS[7]);
		    }if(count>=9) {
		    jp1.add(jt63);
		    jp1.add(jt106);
		    jp1.add(jt64);
		    jp1.add(jt65);
		    jp1.add(jt66);
		    jp1.add(jt67);
		    jp1.add(jt68);
		    jp1.add(jt69);
		    jt106.setText(bus_no1[8]);
		    jt64.setText(Fname[8]);
		    jt65.setText(Lname[8]);
		    jt66.setText(noStationS[8]);
		    jt67.setText(pay_km[8]);
		    jt68.setText(end_kmS[8]);
		    jt69.setText(no_busesS[8]);
		    }if(count>=10) {
		    jp1.add(jt70);
		    jp1.add(jt107);
		    jp1.add(jt71);
		    jp1.add(jt72);
		    jp1.add(jt73);
		    jp1.add(jt74);
		    jp1.add(jt75);
		    jp1.add(jt76);
		    jt107.setText(bus_no1[9]);
		    jt71.setText(Fname[9]);
		    jt72.setText(Lname[9]);
		    jt73.setText(noStationS[9]);
		    jt74.setText(pay_km[9]);
		    jt75.setText(end_kmS[9]);
		    jt76.setText(no_busesS[9]);
		    }if(count>=11) {
		    jp1.add(jt77);
		    jp1.add(jt108);
		    jp1.add(jt78);
		    jp1.add(jt79);
		    jp1.add(jt80);
		    jp1.add(jt81);
		    jp1.add(jt82);
		    jp1.add(jt83);
		    jt108.setText(bus_no1[10]);
		    jt78.setText(Fname[10]);
		    jt79.setText(Lname[10]);
		    jt80.setText(noStationS[10]);
		    jt81.setText(pay_km[10]);
		    jt82.setText(end_kmS[10]);
		    jt83.setText(no_busesS[10]);
		    }if(count>=12) {
			    jp1.add(jt84);
			    jt1.add(jt109);
			    jt84.setText("12");
			    jp1.add(jt85);
			    jp1.add(jt86);
			    jp1.add(jt87);
			    jp1.add(jt88);
			    jp1.add(jt89);
			    jp1.add(jt90);
			    jt109.setText(bus_no1[11]);
			    jt85.setText(Fname[11]);
			    jt86.setText(Lname[11]);
			    jt87.setText(noStationS[11]);
			    jt88.setText(pay_km[11]);
			    jt89.setText(end_kmS[11]);
			    jt90.setText(no_busesS[11]);
			    }if(count>=13) {
				    jp1.add(jt91);
				    jp1.add(jt110);
				    jt91.setText("13");
				    jp1.add(jt92);
				    jp1.add(jt93);
				    jp1.add(jt94);
				    jp1.add(jt95);
				    jp1.add(jt96);
				    jp1.add(jt97);
				    jt110.setText(bus_no1[12]);
				    jt92.setText(Fname[12]);
				    jt93.setText(Lname[12]);
				    jt94.setText(noStationS[12]);
				    jt95.setText(pay_km[12]);
				    jt96.setText(end_kmS[12]);
				    jt97.setText(no_busesS[12]);
				    }
		  
		    // Function to close the operation of JFrame.
		    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		  
		   
		   setSize(1000, 900);
		  
		  
		    jp.add(jp2,BorderLayout.CENTER);
		    jp.add(jp3,BorderLayout.NORTH);
		    jp3.add(jl);
		    jp2.add(jp1);
		    
		    jb0.addActionListener(this);
	        jb01.addActionListener(this);
	        //jb02.addActionListener(this);
	        jb03.addActionListener(this);
	        //jb04.addActionListener(this);
	        back.addActionListener(this);
		    
		    //System.out.println(Lname[0]);
		    setVisible(true);
	}
	
	public void actionPerformed(ActionEvent e)
    {
        String s = e.getActionCommand();
      
        if(s.equals("View spacific root")) {
        	//station id
        	this.setVisible(false);
        	SpecificRoot sr= new SpecificRoot();
        }
        else if(s.equals("View spacific root waiting time")) {
        	//Payment
        	this.setVisible(false);
        	BusTracking bt= new BusTracking();
        }if(s.equals("")){
        	this.setVisible(false);
        	UserForm f = new UserForm(UserForm.userName,UserForm.passWor);
        }
    }

}
